Add readme-fr.md to french users
YunoHost-Apps/wordpress_ynh pull request #101
Opened 2020-06-22 11:50 UTC by Saimyx

Hey ;)

2020-07-03 14:57 UTC, yalh76 submitted a review, later dismissed

2020-07-06 12:45 UTC, ericgaspar requested changes
WordPress naming with cap

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> +Utilisez le panneau d'administration de votre wordpress pour le configurer.
```suggestion
Utilisez le panneau d'administration de votre WordPress pour le configurer.
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> + * Mises à jour automatiques du cœur de wordpress, extentions et thèmes.
```suggestion
 * Mises à jour automatiques du cœur de WordPress, extentions et thèmes.
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> +* Comme les mises à jour automatiques ne fonctionnent pas correctement, prennez soin de bien mettre à jour wordpress via le panneau d'administration de wordpress et pas seulement via le panneau d'adm
```suggestion
* Comme les mises à jour automatiques ne fonctionnent pas correctement, prenez soin de bien mettre à jour WordPress via le panneau d'administration de WordPress et pas seulement via le panneau d'administration de YunoHost. Pour des raisons de sécurité, vérifiez bien que toutes les mises à jour sont bien installées dans le panneau d'administration de WordPress comme dans le panneau d'administration de YunoHost.
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> +Soyez conscients que wordpress est connu pour avoir souvent des risques de sécurité (https://en.wikipedia.org/wiki/WordPress#Vulnerabilities), donc comme c'est le gestionnaire de sites le plus popula
```suggestion
Soyez conscients que WordPress est connu pour avoir souvent des risques de sécurité (https://en.wikipedia.org/wiki/WordPress#Vulnerabilities), donc comme c'est le gestionnaire de sites le plus populaire il est la cible des robots et pirates.
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> +Des vulnérabilités peuvent offrir une brêche dans votre wordpress ou dans votre serveur Yunohost (via l'escalade des droits).
```suggestion
Des vulnérabilités peuvent offrir une brêche dans votre WordPress ou dans votre serveur YunoHost (via l'escalade des droits).
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> +N'oubliez pas d'appliquer tous les bons principes de sécurité (mots de passe forts, mises à jours fréquentes, ne pas ajouter du code inconnu dans le thème et les extensionts…). En particuler, *gardez
```suggestion
N'oubliez pas d'appliquer les principes de sécurité de base (mots de passe forts, mises à jours fréquentes, ne pas ajouter du code inconnu dans le thème et les extensionts…). En particuler, *gardez votre Wordpress à jour le plus possible*.
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> + * Site de Wordpress : https://wordpress.org/
```suggestion
 * Site de WordPress : https://wordpress.org/
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> + * Dépôt de Wordpress : https://core.trac.wordpress.org/browser
```suggestion
 * Dépôt de WordPress : https://core.trac.wordpress.org/browser
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> +> *Ce package vous permet d'installer Wordpress rapidement et simplement sur un serveur YunoHost.
```suggestion
> *Ce package vous permet d'installer WordPress rapidement et simplement sur un serveur YunoHost.  
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> +# Wordpress pour YunoHost
```suggestion
# WordPress pour YunoHost
```

2020-07-06 12:45 UTC, ericgaspar commented on README_fr.md
> +[![Installer Wordpress avec YunoHost](https://install-app.yunohost.org/install-with-yunohost.png)](https://install-app.yunohost.org/?app=wordpress)
```suggestion
[![Installer WordPress avec YunoHost](https://install-app.yunohost.org/install-with-yunohost.png)](https://install-app.yunohost.org/?app=wordpress)
```

2020-07-06 12:45 UTC, ericgaspar commented on README.md
>  > *This package allow you to install wordpress quickly and simply on a YunoHost server.
```suggestion
> *This package allow you to install WordPress quickly and simply on a YunoHost server.  
```

2020-07-06 12:45 UTC, ericgaspar commented on README.md
>  [![Install Wordpress with YunoHost](https://install-app.yunohost.org/install-with-yunohost.png)](https://install-app.yunohost.org/?app=wordpress)
```suggestion
[![Install WordPress with YunoHost](https://install-app.yunohost.org/install-with-yunohost.png)](https://install-app.yunohost.org/?app=wordpress)
```

2020-07-31 13:01 UTC, frju365 submitted a review, later dismissed
LGTM + Code Review

2020-08-14 11:38 UTC, kay0u commented on README_fr.md
> +Par ailleurs, vous pourriez avoir besoin de regarder ce guide :  https://codex.wordpress.org/Hardening_WordPress. Installer des extensions de sécurité peut-être une bonne chose.
```suggestion
Par ailleurs, vous pourriez avoir besoin de regarder [ce guide](https://wordpress.org/support/article/hardening-wordpress/). Installer des extensions de sécurité peut-être une bonne chose.
```

2020-09-03 07:28 UTC, kay0u approved these changes

2020-09-03 07:29 UTC, merged