Testing
YunoHost-Apps/wordpress_ynh pull request #108
Opened 2020-08-15 08:29 UTC by kay0u

## Problem
- *App not up to date*

## Solution
- *Update to 5.5*
- *Update link to hardening Wordpress guide*
- *Fix typo the readme*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- [ ] **Code review** : 
- [ ] **Approval (LGTM)** :  
*Code review and approval have to be from a member of @YunoHost-Apps/apps-group*
- **CI succeeded** : 
[![Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/wordpress_ynh%20PR-NUM-/badge/icon)](https://ci-apps-hq.yunohost.org/jenkins/job/wordpress_ynh%20PR-NUM-/)  
*Please replace '-NUM-' in this link by the PR number.*  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

2020-09-04 00:43 UTC, yalh76 requested changes

2020-09-04 00:43 UTC, yalh76 commented on README_fr.md
> +**Version incluse :** 5.4
version has not been upgraded to 5.5

2020-09-04 00:43 UTC, yalh76 commented on README_fr.md
> +* x86-64b - [![](https://ci-apps.yunohost.org/ci/logs/wordpress%20%28Apps%29.svg)](https://ci-apps.yunohost.org/ci/apps/wordpress/)
```suggestion
* x86-64 - [![](https://ci-apps.yunohost.org/ci/logs/wordpress%20%28Apps%29.svg)](https://ci-apps.yunohost.org/ci/apps/wordpress/)
```

2020-09-04 17:31 UTC, yalh76 approved these changes

2020-09-07 13:15 UTC, kay0u commented
Merging in 3 days

2020-09-11 09:09 UTC, merged