fix maintenance
YunoHost-Apps/wordpress_ynh pull request #228
Opened 2023-08-28 07:44 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-08-28 07:44 UTC, ericgaspar commented
!testme

2023-08-31 21:25 UTC, tituspijean requested changes, later dismissed
Additionally, somehow the `__PHPVERSION__` in the FPM config file gets replaced by `7.4` instead of `8.2` while running the config panel, breaking the app. I have found no explanation for it.

2023-08-31 21:25 UTC, tituspijean commented on scripts/config
>          ynh_print_info "Maintenance mode disabled"
```suggestion
        ynh_print_info "Maintenance mode enabled"
```

2023-08-31 21:25 UTC, tituspijean commented on scripts/config
>          ynh_print_info "Maintenance mode enabled"
```suggestion
        ynh_print_info "Maintenance mode disabled"
```

2023-08-31 21:25 UTC, tituspijean commented on scripts/config
>              echo "Site under maintenance." > .maintenance)
```suggestion
        ynh_exec_as "$app" echo "Site under maintenance." > $install_dir/.maintenance)
```

2023-09-01 06:51 UTC, tituspijean commented on scripts/config
>              echo "Site under maintenance." > .maintenance)
Oh, I did not check files permissions with my altered command.

2023-09-11 10:48 UTC, ericgaspar commented
!testme

2023-10-31 14:48 UTC, ericgaspar commented
!testme

2023-11-22 18:00 UTC, alexAubin approved these changes

2023-11-28 01:02 UTC, merged