Allow specifying PHP version #223
YunoHost-Apps/wordpress_ynh pull request #229
Opened 2023-10-07 19:28 UTC by fflorent

## Problem

- Some plugins are not compatible yet with PHP 8.2 and make wordpress crash

## Solution

- Allow the user specifying the PHP version 

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

closes #223

2023-10-11 17:38 UTC, fflorent commented
!testme

2023-10-11 21:12 UTC, fflorent commented
!testme

2023-10-11 22:40 UTC, alexAubin requested changes
Personally, as expressed in the corresponding issue if i recall correctly, I'm against this change

This is against YunoHost's spirit : asking a technical question which ncreases the complexity of install in terms of both UI/UX and technically, equals bloat, and YunoHost is supposed to be KISS.

If some plugins are really *that* important then the YunoHost package should stick to some version that is compatible with those. If they aint important and are already for specific need then : YunoHost can't cover every possible need, and you people could stick to an older version of the app/package until their plugin is compatible.

2023-10-11 22:59 UTC, alexAubin commented on manifest.toml
> +    default = "8.2"
Or i dunno, we should at least add an `help` key explaining that the default value is fine for regular use case and that some plugins are only compatible with older versions of php...

2023-10-11 22:59 UTC, Tagadda commented
I think that we shouldn't ask PHP version when installing Wordpress.
If we need to change the PHP version, I think the config panel is the good place for this setting.

2023-10-12 06:00 UTC, fflorent commented
I think we need to somehow propose the PHP version, as some plugins cannot be removed easily and still need PHP version < 8.1. Unless we are OK with downgrading the PHP version (however not sure if that's a good idea).

I like the proposal of proposing the option through the config panel, however I am not sure how simple it is to implement that (having to move the pool configuration file to a PHP version to another, reload or restart the previous and the new FPM service, removing the old dependencies and reinstalling the dependencies according to the new version, etc.).

2023-10-12 09:27 UTC, Tagadda commented
my_weppapp_ynh does this already o/
https://github.com/YunoHost-Apps/my_webapp_ynh/blob/master/config_panel.toml#L24-L28
https://github.com/YunoHost-Apps/my_webapp_ynh/blob/master/scripts/config#L113-L136

2023-10-16 08:14 UTC, fflorent commented
Thanks for the hint @Tagadda!

App dependencies do not seem to be all reinstalled: https://github.com/YunoHost-Apps/my_webapp_ynh/issues/131 

I opened this PR, though I wonder if something simpler could be done: https://github.com/YunoHost-Apps/my_webapp_ynh/pull/130/files

I guess similar issue would exist for Wordpress if the php version could be changed through the config panel.

2025-12-18 20:34 UTC, ericgaspar commented
closing by popular demand

2025-12-18 20:34 UTC, closed without merging