Update link to hardening Wordpress guide
YunoHost-Apps/wordpress_ynh pull request #97
Opened 2020-06-04 08:34 UTC by nqb

## Problem
Old link is outdated.

## Solution
Update link.

## PR Status
- [X] Code finished.

2020-07-03 14:48 UTC, yalh76 requested changes

2020-07-03 14:48 UTC, yalh76 commented on README.md
> +Furthermore, you might take a look at the [Hardening Wordpress Guide](https://codex.wordpress.org/Hardening_WordPress). You might see some benefits in the use of wordpress security plugins.
Seems link has been moved to https://wordpress.org/support/article/hardening-wordpress/

2020-07-06 05:44 UTC, nqb commented
Hello @yalh76,

It looks like I missed to copy the link. I did it now.

2020-07-07 19:42 UTC, yalh76 approved these changes

2020-08-14 11:29 UTC, kay0u approved these changes

2020-08-14 11:29 UTC, merged